server:
  port: 8009
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:bookingdb
    driver-class-name: org.h2.Driver
    username: sa
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  show-sql: true

conference-room:
  maintenance-timings:
    - startTime: "09:00"
      endTime: "09:15"
    - startTime: "13:00"
      endTime: "13:15"
    - startTime: "17:00"
      endTime: "17:15"
  booking:
    interval: 15
